### ISSUE TITLE
"LexerAdaptor" is missing When I run this package

### ISSUE THREAD

**Issue by DancingOnAir** [wadoon/antlr2sitter#1]
Hi, Waddon. I want to convert Anltr file into the grammar.js of tree-sitter by this python package. I installed it by `pip install .`, and I ran the command `antlr2sitter LuaParser.g4` or `antlr2sitter LuaLexer.g4`, it showed some errors as below:
`Traceback (most recent call last):
  File "/Users/abc/opt/anaconda3/envs/antlr2sitter/bin/antlr2sitter", line 5, in <module>
    from antlr2sitter.__main__ import main
  File "/Users/abc/opt/anaconda3/envs/antlr2sitter/lib/python3.9/site-packages/antlr2sitter/__init__.py", line 1, in <module>
    from antlr2sitter.ANTLRv4Lexer import ANTLRv4Lexer
  File "/Users/abc/opt/anaconda3/envs/antlr2sitter/lib/python3.9/site-packages/antlr2sitter/ANTLRv4Lexer.py", line 12, in <module>
    from .LexerAdaptor import LexerAdaptor
ModuleNotFoundError: No module named 'antlr2sitter.LexerAdaptor'`

I can't find the reference of "LexerAdaptor" in the code, it seems the super class. Could you guide me how to solve this issue? Thank you

**Comment by ndimiduk** [comment]
I think they forgot to add this file to the repo with the last commit.

**Comment by dacec354** [comment]
same problem
